In [6]:
import pandas as pd

In [8]:
import os
print(os.getcwd())
print(os.listdir())

/content
['.config', 'quotes .csv', '.ipynb_checkpoints', 'sample_data']

In [9]:
import pandas as pd

df = pd.read_csv("quotes .csv")
df.head()

                                               Quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Quote   10 non-null     object
 1   Author  10 non-null     object
dtypes: object(2)
memory usage: 292.0+ bytes

In [11]:
df.describe(include="all")

                                                    Quote           Author
count                                                  10               10
unique                                                 10                8
top     “The world as we have created it is a process ...  Albert Einstein
freq                                                    1                3

In [12]:
df.isnull().sum()

Quote     0
Author    0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

# Observations

1. The dataset contains quotes and their respective authors.
2. There are 2 columns: Quote and Author.
3. There are no missing values in the dataset.
4. There are no duplicate records.
5. The dataset is clean and ready for analysis and visualization.

In [14]:
df.to_csv("EDA_Output.csv", index=False)

print("EDA Output Saved Successfully!")

EDA Output Saved Successfully!